POST http://localhost:3000/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyNzA1Njk5LCJ1c2VyIjoxMDAwMH0.ySP6KRdGey0tt2OvNlqcmfZX7EltqN_REW47HueaIfQ

{
    "name": "Company-a2",
    "email": "company_a2.doe@example.com",
    "phone": "05131321523"
}