GET http://localhost:3000/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyNzAyNzg5LCJ1c2VyIjoxMDAwMH0.5RGV4OpMLsnrVcE66S1suPO6sv0Mt1S7_eMjbczIN_0