GET http://localhost:3000/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyNjkzMzQ5LCJ1c2VyIjoxMDAwMH0.azY5sAu-CZA7MsFnRTD_BmsQnK_TNxwIhacXIQoboec
