POST http://localhost:3000/project
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyNzA1Njk5LCJ1c2VyIjoxMDAwMH0.ySP6KRdGey0tt2OvNlqcmfZX7EltqN_REW47HueaIfQ

{
    "name": "Photo shape",
    "price": 2500.99,
    "startDate": "2026-07-01T18:00:00Z",
    "endDate": "2026-07-31T18:00:00Z"
}