GET http://localhost:3000/project/10002
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzgyNjk5MjI1LCJ1c2VyIjoxMDAwMH0.VqcfIBOGhR39IWlMsyLXb6GYJRrApdUcuAfpVYLkrRc